version: "3.8"
services:
    alpine:
        build:
            context: ./project-manager
            dockerfile: Dockerfile
        container_name: project_manager_php
        restart: on-failure
        ports:
            - "1234:80"
        volumes:
            - ./conf/site.conf:/etc/nginx/http.d/default.conf
            - ./project-manager:/var/www/html
        networks:
            - acpSymfony

    db:
        image: mariadb:10.8.2
        container_name: project_manager_db
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
        networks:
            - acpSymfony

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: project_manager_pma
        restart: always
        ports:
            - '8080:80'
        environment:
            # demande le nom du server
            #- PMA_ARBITRARY=1
            # Pour ne pas avoir à préciser le nom du server
            - PMA_HOST=db
            - PMA_PASSWORD=${PMA_PASS}
        depends_on:
            - db
        networks:
            - acpSymfony
            
    client:
        image: simple-react-client
        build:
            context: ./client
            dockerfile: Dockerfile
        container_name: project_manager_client
        volumes:
            - ./client:/app
            - /app/node_modules
        ports:
            - "3000:3000"
        networks:
            - acpSymfony
        environment:
            - WATCHPACK_POLLING=true
                
    backoffice:
        image: next-img
        build:
            context: ./client-ssr
            dockerfile: Dockerfile
        container_name: project_manager_client_ssr
        volumes:
            - ./client-ssr:/app
            - /app/node_modules
        ports:
           - "3001:3000" 
        networks:
            - acpSymfony
            

volumes:
    db-data:

networks:
    acpSymfony:
