nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:3000'] # Add your frontend URL here
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 3600
        origin_regex: true
        forced_allow_origin_value: ~
    paths:
        '^/api': ~